# Generated by Django 4.0.4 on 2022-05-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_testimonials_alter_slider_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='img',
            field=models.ImageField(upload_to='index/Testimonials'),
        ),
    ]
