# Generated by Django 4.0.4 on 2022-05-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_testimonials_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_available',
            field=models.BooleanField(default=True, null=True, verbose_name='Published'),
        ),
    ]
