# Generated by Django 4.0.4 on 2022-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_slider_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
