# Generated by Django 4.0.4 on 2022-05-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='size')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('info', models.TextField(max_length=700, verbose_name='information ')),
                ('price', models.IntegerField(verbose_name='price')),
                ('cart_detail', models.TextField(max_length=700, verbose_name='cart details')),
                ('is_available', models.BooleanField(default=True, verbose_name='vailable')),
                ('shiping_returns', models.TextField(max_length=1000, verbose_name='shiping and returns')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('feedback', models.IntegerField(verbose_name='FeedBack')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='products.size')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='category name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
